### ISSUE TITLE
npm install wont work

### ISSUE THREAD

**Issue by chrisvidal** [cjkpl/oc-tabularasa-theme#3]
```
> fsevents@1.2.13 install /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/laravel-mix/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/laravel-mix/node_modules/fsevents
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/christophevidal/Sites/oc-azalea/themes/oc-azalea-theme/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for cross-env@7.0.3: wanted: {"node":">=10.14","npm":">=6","yarn":">=1"} (current: {"node":"10.10.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: cross-env@7.0.3
npm WARN notsup Unsupported engine for @tailwindcss/postcss7-compat@2.0.2: wanted: {"node":">=12.13.0"} (current: {"node":"10.10.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: @tailwindcss/postcss7-compat@2.0.2
npm WARN notsup Unsupported engine for laravel-mix-purgecss@5.0.0: wanted: {"node":">=12.0.0"} (current: {"node":"10.10.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: laravel-mix-purgecss@5.0.0
npm WARN notsup Unsupported engine for postcss-purgecss-laravel@0.1.2: wanted: {"node":">=12.0.0"} (current: {"node":"10.10.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: postcss-purgecss-laravel@0.1.2
npm WARN tabularasa@2.0.0 No repository field.

added 1339 packages from 628 contributors in 25.131s
```

**Comment by chrisvidal** [comment]
for anyone else encountering the issue:
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
